### ISSUE TITLE
Help needed.

### ISSUE THREAD

**Issue by thisisamardeep** [juxeii/JForexUtils#1]
Hi Sir

Regarding your git project https://github.com/juxeii/JForexUtils.git.

I have written my own code i java and i just need to be able to place
orders  from my code.
I dont want to have any strategies in my code.I am able to connect to
my account but not able to place orders.Can you please point me in the
right direction.

    public static void main(String[] args) throws Exception {
        //get the instance of the IClient interface
        client = ClientFactory.getDefaultInstance();

        setSystemListener();
        tryToConnect();
        subscribeToInstruments();
        // i need to place a market order here

    }

**Comment by juxeii** [comment]
It is not clear to me what you want to do.
If it is just about opening a market order, please see the documentation at the Dukascopy [website.](https://www.dukascopy.com/wiki/en/development/strategy-api/orders-and-positions/market-order)

**Comment by thisisamardeep** [comment]
Hi Sir
As per website  to open a order we need instance of iengine.Example below

IOrder order = engine.submitOrder("MyMaketBuyOrder", Instrument.EURUSD, OrderCommand.BUY, 0.1);
In my code how can i get instance of iengine.In a strategy in the onstart method we get a instance of Icontext which can be used to get iengine object and then place order as below. 
Sample onstart method of a strategy.

public void onStart(IContext context) throws JFException {
        engine = context.getEngine();
        indicators = context.getIndicators();
        this.console = context.getConsole();
        this.context=context;
      //  context.setSubscribedInstruments(new HashSet<Instrument>(Arrays.asList(Instrument.EURUSD), true));
    //    context.setSubscribedInstruments(new HashSet<Instrument>(Arrays.asList(Instrument.EURUSD, Instrument.AUDCAD), true));
        context.setSubscribedInstruments(new HashSet<Instrument>(Arrays.asList(Instrument.EURUSD)));
        console.getOut().println("Started");
    }
But how do i do this from my code as below.

public static void main(String[] args) throws Exception {
    //get the instance of the IClient interface
    client = ClientFactory.getDefaultInstance();

    setSystemListener();
    tryToConnect();
    subscribeToInstruments();
    // i need to place a market order here
/// how do i get instance of iengine here to place order.

}
Hope i am able to explain the issue.

**Comment by juxeii** [comment]
You need an instance of [IStrategy](https://www.dukascopy.com/client/javadoc/com/dukascopy/api/IStrategy.html) to get the [IEngine](https://www.dukascopy.com/client/javadoc/com/dukascopy/api/IEngine.html) instance.
So you need to implement the IStrategy interface. I am not aware of any method for directly opening an order without a strategy.
Please see the Dukascopy manuals on how to do all this.
